### PR TITLE
Pull E3SM's maint-3.0

### PR DESCRIPTION
**Pull request by GrahamBenHarper**
@wagmanbe we're already out of sync with E3SM's `maint-3.0` branch, so we'll pull down a few commits before we grab Jim's mods.

FYI, in the future if we want to pull down more commits from E3SM's `maint-3.0` branch with another PR, we can just use this link: [https://github.com/sandialabs/E3SMFC/compare/maint-3.0...E3SM-Project:E3SM:maint-3.0](https://github.com/sandialabs/E3SMFC/compare/maint-3.0...E3SM-Project:E3SM:maint-3.0)

### CODE REVIEW

**Review by wagmanbe — COMMENTED** [review]
Will approve. The only question is whether you prefer "merge" "squash and merge" or "rebase". I would think rebase is the way to go. But I think maybe you cautioned against that?

**Comment by GrahamBenHarper** [comment]
@wagmanbe oh good question! Actually for these merge requests it's better to rebase and merge. The problem we had with CLDERA-E3SM was we rebased the whole repository instead of rebasing a pull request, which messed up the things that had previously been merged. I think for this repository, we'll do the following:
 - All E3SM maint-3.0 pull requests fall under "rebase and merge"
 - All E3SMFC specific pull requests just fall under "merge pull request"
 - And we'll basically never use the "squash and merge" option unless we make E3SMFC changes that are 10 small commits that are more useful to squash into just 1 commit

Hopefully that helps!

**Comment by wagmanbe** [comment]
Rebasing and merging. Next we can bring in jimsmods.

**Comment by GrahamBenHarper** [comment]
@wagmanbe wait, maybe I lied and the rebase option is the wrong one. Maybe we really do just want "merge pull request" for everything! Let me double-check something...

**Pull request merged**
